### ISSUE TITLE
Wrong degree info

### ISSUE THREAD

**Issue by foxyseta** [cartabinaria/isi-computational-statistics#2]
`README.md` and the repo "About" section (right sidebar of the repo's homepage) wrongly suggest this teaching to be from the Informatics degree, while the `isi-` prefix in the repo's name [wrongly suggests it to be from the Computer Science and Engineering course in Cesena](https://cartabinaria.students.cs.unibo.it/en/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/). This course [appears to be from the Statistical Sciences degree](https://www.unibo.it/en/study/phd-professional-masters-specialisation-schools-and-other-programmes/course-unit-catalogue/course-unit/2023/454724), which would have been easier to look up if the repo's README and about section also contained the teaching ID.

This is due to @kocierik swiftly approving @giospada's https://github.com/cartabinaria/config/pull/33. I am assuming @Diebbo is currently taking the course, so he can correct me if I am making any false claims here.

I think we should:
- change the "About" section of the repo so that:
  - [x] it is in English
  - [x] mentions Statistical Sciences, rather than Informatics/Computer Science
  - [x] refers to the teaching as "Computational Statistics (79192)", rather than just "Computational Statistics"
- change the "README"so that:
  - [x] mentions Statistical Sciences, rather than Informatics/Computer Science
  - [x] refers to the teaching as "Computational Statistics (79192)", rather than just "Computational Statistics", both in the title and the body
- finally:
  - [x] rename the repo to just `computational-statistics` (or ask @ali-benny / @samuelemusiani if a prefix is needed. I assume no, as there are no naming clashes)
  - [x] use the new repository name in `teachings.json` and `degrees.json` via a PR to https://github.com/cartabinaria/

**Comment by ali-benny** [comment]
> * rename the repo to just `computational-statistics` (or ask @ali-benny / @samuelemusiani if a prefix is needed. I assume no, as there are no naming clashes)

I believe no prefix is necessary in this case, as there don’t appear to be any naming conflicts:
![immagine](https://github.com/user-attachments/assets/ba9cf19b-04eb-4a80-836a-999747c169a6)

**Comment by Diebbo** [comment]
think you are right @foxyseta, i can take care of this

**Comment by foxyseta** [comment]
Thanks! I added you to @cartabinaria/informatica-3, which is the group required to maintain 3rd year courses from your degree. You'll need it to rename this repository and change the "About" section, I believe.

**Comment by Diebbo** [comment]
i noticed that i don't have the access rights to change the course name! @foxyseta

**Comment by foxyseta** [comment]
Probably something only admins can do then? Cannot find this specific piece of information on GitH*b docs: https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

Feel free to ping me right after Dynamik and Informabot are updated then. I'll take care of it.

**Comment by Diebbo** [comment]
i don't know in deep how informabot and dynamic work. Are they automatically updating after the ci/cd on pr of the config repo?

**Comment by foxyseta** [comment]
Yes, @dependabot will create PRs to uodate the commit of this repo those projects are using.
